apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: backend-secrets
  namespace: backend
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: backend-infisical-auth
        secretNamespace: backend
  managedSecretReference:
    secretName: backend-generated-secrets
    secretNamespace: backend
  projectId: "eaa2be30-8c84-4edb-a020-179d170cc682"
  environment: "prod"