apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: backend-secrets
  namespace: backend
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: backend-infisical-auth
        secretNamespace: backend
      secretsScope:
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: backend-generated-secrets
    secretNamespace: backend