apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: frontend-secrets
  namespace: frontend
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: frontend-infisical-auth
        secretNamespace: frontend
      secretsScope:
        projectId: "eaa2be30-8c84-4edb-a020-179d170cc682"
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: frontend-generated-secrets
    secretNamespace: frontend