apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: postgres-infisical-auth
        secretNamespace: postgres
  managedSecretReference:
    secretName: postgres-generated-secrets
    secretNamespace: postgres
  projectId: "eaa2be30-8c84-4edb-a020-179d170cc682"
  environment: "prod"