apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: postgres-infisical-auth
        secretNamespace: postgres
      secretsScope:
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: postgres-generated-secrets
    secretNamespace: postgres